package contohkasus;
/*
    * This Java source file was generated by the Gradle 'init' task.
*/

    public class App {

    public static void main(String[] args) {
        Customer customer1 = new Customer("Wanwan", "lampung");
        Order order1 = new Order("pisang cokelat" , 17000, 5);
        customer1.order(order1);

        Customer customer2 = new Customer("Jono", "Bali");
        Order order2 = new Order("Daging", 15000, 2);
        customer2.order(order2);


    }
}
